# Generated by Django 5.1.2 on 2024-11-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanings', '0002_rename_auther_book_author_rename_type_book_book_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
